import jsPDF from "jspdf";
import "jspdf-autotable";

// Colors
const primaryColor = [27, 67, 50]; // #1B4332 - Venueza dark green
const accentColor = [22, 163, 74]; // Green for amounts
const textDark = [15, 23, 42]; // Slate 900
const textLight = [100, 116, 139]; // Slate 500

const drawHeader = (doc, title, booking) => {
  // Header background
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, 210, 40, "F");

  // Logo / Brand
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("VENUEZA", 14, 25);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Premium Venue & Event Management", 14, 32);

  // Title & Info
  doc.setFontSize(22);
  doc.text(title, 196, 25, { align: "right" });
  doc.setFontSize(10);
  doc.text(`Booking Ref: ${booking.bookingId}`, 196, 32, { align: "right" });
};

const drawFooter = (doc) => {
  const pageHeight = doc.internal.pageSize.height;
  doc.setFillColor(248, 250, 252);
  doc.rect(0, pageHeight - 20, 210, 20, "F");
  
  doc.setTextColor(...textLight);
  doc.setFontSize(9);
  doc.text("Thank you for choosing Venueza.", 105, pageHeight - 11, { align: "center" });
  doc.text("Generated by Venueza ERP System", 105, pageHeight - 6, { align: "center" });
};

export const generateQuotation = (data) => {
  const doc = new jsPDF();
  const { booking } = data;
  
  drawHeader(doc, "QUOTATION", booking);
  
  // Customer Info
  doc.setTextColor(...textDark);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Quotation For:", 14, 55);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`Name: ${booking.Customer?.name || booking.customerName || "N/A"}`, 14, 62);
  doc.text(`Phone: ${booking.Customer?.phone || booking.phone || "N/A"}`, 14, 68);
  
  // Event Info
  doc.setFont("helvetica", "bold");
  doc.text("Event Details:", 120, 55);
  doc.setFont("helvetica", "normal");
  doc.text(`Date: ${new Date(booking.date).toLocaleDateString()}`, 120, 62);
  doc.text(`Event: ${booking.eventType || "N/A"}`, 120, 68);
  doc.text(`Hall: ${booking.hall || "N/A"} (${booking.session || "Full Day"})`, 120, 74);
  doc.text(`Guests: ${booking.guests || 0}`, 120, 80);

  // Pricing Table
  doc.autoTable({
    startY: 90,
    headStyles: { fillColor: primaryColor, textColor: 255 },
    head: [["Description", "Amount (INR)"]],
    body: [
      ["Base Hall Rental", `Rs. ${booking.totalAmount?.toLocaleString() || 0}`],
      ["Discount", `Rs. ${booking.discount?.toLocaleString() || 0}`],
      ["Taxes", `Rs. ${booking.taxes?.toLocaleString() || 0}`],
    ],
    foot: [
      ["Total Estimate", `Rs. ${booking.totalAmount?.toLocaleString() || 0}`]
    ],
    footStyles: { fillColor: [241, 245, 249], textColor: textDark, fontStyle: "bold" },
    theme: "grid"
  });

  drawFooter(doc);
  doc.save(`Quotation_${booking.bookingId}.pdf`);
};

export const generateAgreement = (data) => {
  const doc = new jsPDF();
  const { booking } = data;
  
  drawHeader(doc, "BOOKING AGREEMENT", booking);
  
  doc.setTextColor(...textDark);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Terms & Conditions of Booking", 14, 55);
  
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  const text = `This agreement is made between Venueza and ${booking.Customer?.name || booking.customerName}. 
  
Event Date: ${new Date(booking.date).toLocaleDateString()}
Event Type: ${booking.eventType}
Hall: ${booking.hall}

1. The total agreed amount for the booking is Rs. ${booking.totalAmount?.toLocaleString() || 0}.
2. An advance payment of Rs. ${booking.advance?.toLocaleString() || 0} has been noted.
3. The remaining balance of Rs. ${data.outstanding?.toLocaleString() || 0} must be cleared before the event.
4. Standard cancellation policies apply as per venue rules. Advance payments may be non-refundable.
5. Any damages to the property during the event will be charged additionally.
6. The venue is provided for the specified session (${booking.session || "Full Day"}).

By proceeding with the booking, both parties agree to these terms.


Signed: _______________________                   Date: ______________
(Customer)

Signed: _______________________                   Date: ______________
(Venueza Authorized Signatory)
`;

  doc.text(text, 14, 65, { maxWidth: 180, lineHeightFactor: 1.6 });
  
  drawFooter(doc);
  doc.save(`Agreement_${booking.bookingId}.pdf`);
};

export const generateInvoice = (data) => {
  const doc = new jsPDF();
  const { booking, payments, totalPaid, outstanding } = data;
  
  drawHeader(doc, "FINAL TAX INVOICE", booking);
  
  // Invoice Info
  doc.setTextColor(...textDark);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Bill To:", 14, 55);
  doc.setFont("helvetica", "normal");
  doc.text(`${booking.Customer?.name || booking.customerName}`, 14, 62);
  doc.text(`Phone: ${booking.Customer?.phone || booking.phone}`, 14, 68);
  
  doc.setFont("helvetica", "bold");
  doc.text("Invoice Details:", 120, 55);
  doc.setFont("helvetica", "normal");
  doc.text(`Status: ${outstanding <= 0 ? "PAID" : "DUE"}`, 120, 62);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 120, 68);

  // Summary Table
  doc.autoTable({
    startY: 80,
    headStyles: { fillColor: primaryColor, textColor: 255 },
    head: [["Item Description", "Amount (INR)"]],
    body: [
      [`Event Booking: ${booking.eventType} at ${booking.hall}`, `Rs. ${booking.totalAmount?.toLocaleString() || 0}`]
    ],
    foot: [
      ["Gross Total", `Rs. ${booking.totalAmount?.toLocaleString() || 0}`],
      ["Total Paid", `Rs. ${totalPaid?.toLocaleString() || 0}`],
      ["Balance Due", `Rs. ${outstanding?.toLocaleString() || 0}`]
    ],
    footStyles: { fillColor: [248, 250, 252], textColor: textDark, fontStyle: "bold" },
    theme: "grid"
  });

  // Payment History
  if (payments && payments.length > 0) {
    doc.text("Payment History", 14, doc.lastAutoTable.finalY + 15);
    const payBody = payments.map(p => [
      new Date(p.createdAt).toLocaleDateString(),
      p.Receipt?.receiptNumber || "-",
      p.paymentMode,
      `Rs. ${p.amount.toLocaleString()}`
    ]);
    
    doc.autoTable({
      startY: doc.lastAutoTable.finalY + 20,
      headStyles: { fillColor: [100, 116, 139] },
      head: [["Date", "Receipt No", "Mode", "Amount"]],
      body: payBody,
      theme: "grid"
    });
  }

  drawFooter(doc);
  doc.save(`Invoice_${booking.bookingId}.pdf`);
};

export const generateReceiptSummary = (data) => {
  const doc = new jsPDF();
  const { booking, payments } = data;
  
  drawHeader(doc, "RECEIPT SUMMARY", booking);
  
  doc.setTextColor(...textDark);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(`Payment Ledger`, 14, 55);
  
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`Customer: ${booking.Customer?.name || booking.customerName}`, 14, 65);
  doc.text(`Total Paid: Rs. ${data.totalPaid?.toLocaleString() || 0}`, 14, 72);

  if (!payments || payments.length === 0) {
    doc.text("No payments recorded yet.", 14, 90);
  } else {
    const payBody = payments.map(p => [
      new Date(p.createdAt).toLocaleDateString(),
      p.Receipt?.receiptNumber || "-",
      p.paymentMode,
      `Rs. ${p.amount.toLocaleString()}`
    ]);
    
    doc.autoTable({
      startY: 85,
      headStyles: { fillColor: primaryColor, textColor: 255 },
      head: [["Date", "Receipt No", "Mode", "Amount"]],
      body: payBody,
      theme: "grid"
    });
  }
  
  drawFooter(doc);
  doc.save(`Receipts_${booking.bookingId}.pdf`);
};

export const generateStatement = (data) => {
  const doc = new jsPDF();
  const { booking, payments } = data;
  
  drawHeader(doc, "CUSTOMER STATEMENT", booking);
  
  doc.setTextColor(...textDark);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(`Booking Ledger Statement`, 14, 55);
  
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`Customer: ${booking.Customer?.name || booking.customerName}`, 14, 65);
  doc.text(`Date Generated: ${new Date().toLocaleDateString()}`, 14, 72);

  const statementBody = [
    [
      new Date(booking.date).toLocaleDateString(),
      "Booking Finalized (Gross Amount)",
      `Rs. ${booking.totalAmount?.toLocaleString() || 0}`,
      "-",
      `Rs. ${booking.totalAmount?.toLocaleString() || 0}`
    ]
  ];

  let runningBalance = booking.totalAmount || 0;
  
  if (payments && payments.length > 0) {
    const sortedPayments = [...payments].sort((a, b) => new Date(a.createdAt) - new Date(b.createdAt));
    sortedPayments.forEach(p => {
      runningBalance -= p.amount;
      statementBody.push([
        new Date(p.createdAt).toLocaleDateString(),
        `Receipt #${p.Receipt?.receiptNumber || "-"} (${p.paymentMode})`,
        "-",
        `Rs. ${p.amount.toLocaleString()}`,
        `Rs. ${runningBalance.toLocaleString()}`
      ]);
    });
  }
  
  doc.autoTable({
    startY: 85,
    headStyles: { fillColor: primaryColor, textColor: 255 },
    head: [["Date", "Particulars", "Debit", "Credit", "Balance"]],
    body: statementBody,
    theme: "grid"
  });
  
  drawFooter(doc);
  doc.save(`Statement_${booking.bookingId}.pdf`);
};

export const generateReceipt = (payment, booking) => {
  const doc = new jsPDF();
  
  drawHeader(doc, "PAYMENT RECEIPT", booking);
  
  doc.setTextColor(...textDark);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(`Receipt #: ${payment.Receipt?.receiptNumber || "-"}`, 14, 55);
  
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Received with thanks from: ${booking.Customer?.name || booking.customerName}`, 14, 70);
  doc.text(`The sum of: Rs. ${payment.amount.toLocaleString()}`, 14, 80);
  doc.text(`Payment Mode: ${payment.paymentMode}`, 14, 90);
  doc.text(`Date: ${new Date(payment.createdAt).toLocaleDateString()}`, 14, 100);
  doc.text(`For Booking Ref: ${booking.bookingId}`, 14, 110);
  
  doc.setFont("helvetica", "bold");
  doc.text("Authorized Signature", 150, 140);
  
  drawFooter(doc);
  doc.save(`Receipt_${payment.Receipt?.receiptNumber || payment.id}.pdf`);
};
