import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { settingsAPI } from "../services/api";

const getSettings = async () => {
  try {
    const res = await settingsAPI.get();
    return res.data?.data || {};
  } catch (e) {
    return {};
  }
};

const fetchImage = (url) => {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = "Anonymous";
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext("2d");
      ctx.drawImage(img, 0, 0);
      resolve(canvas.toDataURL("image/png"));
    };
    img.onerror = reject;
    img.src = url;
  });
};

// Colors
const primaryColor = [27, 67, 50]; // #1B4332 - Venueza dark green
const accentColor = [22, 163, 74]; // Green for amounts
const textDark = [15, 23, 42]; // Slate 900
const textLight = [100, 116, 139]; // Slate 500

const drawHeader = async (doc, title, booking, settings = {}) => {
  // Header background
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, 210, 44, "F");

  // Logo / Brand
  doc.setTextColor(255, 255, 255);
  
  let textX = 14;
  if (settings.logoUrl) {
    try {
      const imgData = await fetchImage(settings.logoUrl);
      // Logo sized to match heading text height (top of logo = top of heading, bottom = bottom of heading)
      doc.addImage(imgData, 'PNG', 14, 10, 24, 24);
      textX = 42;
    } catch (e) {
      console.warn("Failed to load logo", e);
    }
  }

  // Left side — Venue info (vertically centered: y=12 to y=36)
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(settings.venueName || "VENUEZA", textX, 14);
  
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text(settings.location || "Premium Venue & Event Management", textX, 20);
  
  let contactStr = [];
  if (settings.phone) contactStr.push(settings.phone);
  if (settings.email) contactStr.push(settings.email);
  
  if (contactStr.length > 0) {
    doc.text(contactStr.join(" | "), textX, 26);
  }

  if (settings.gstin) {
    doc.text(`GSTIN: ${settings.gstin}`, textX, 32);
  }

  // Right side — Document title (vertically centered)
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(title, 196, 22, { align: "right" });
};

const drawFooter = (doc, settings = {}) => {
  const pageHeight = doc.internal.pageSize.height;
  doc.setFillColor(248, 250, 252);
  doc.rect(0, pageHeight - 20, 210, 20, "F");
  
  doc.setTextColor(...textLight);
  doc.setFontSize(9);
  doc.text(`Thank you for choosing ${settings.venueName || "Venueza"}.`, 105, pageHeight - 11, { align: "center" });
  doc.text("Generated by Venueza ERP System", 105, pageHeight - 6, { align: "center" });
};

export const generateQuotation = async (data) => {
  const doc = new jsPDF();
  const { booking } = data;
  const settings = await getSettings();
  
  await drawHeader(doc, "QUOTATION", booking, settings);
  
  // Customer Info
  doc.setTextColor(...textDark);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Quotation For:", 14, 55);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`Name: ${booking.Customer?.name || booking.customerName || "N/A"}`, 14, 62);
  doc.text(`Phone: ${booking.Customer?.phone || booking.phone || "N/A"}`, 14, 68);
  const clientGst = booking.clientGstNumber || booking.Customer?.gstNumber;
  if (clientGst && clientGst !== "undefined" && clientGst !== "null") {
    doc.text(`GSTIN: ${clientGst}`, 14, 74);
  }
  
  // Event Info
  doc.setFont("helvetica", "bold");
  doc.text("Event Details:", 120, 55);
  doc.setFont("helvetica", "normal");
  doc.text(`Booking Ref: ${booking.bookingId || booking.id}`, 120, 62);
  doc.text(`Date: ${new Date(booking.date).toLocaleDateString()}`, 120, 68);
  doc.text(`Event: ${booking.eventType || "N/A"}`, 120, 74);
  doc.text(`Hall: ${booking.hall || "N/A"} (${booking.session || "Full Day"})`, 120, 80);
  doc.text(`Guests: ${booking.guests || 0}`, 120, 86);

  // Pricing Table
    autoTable(doc, {
    startY: 90,
    headStyles: { fillColor: primaryColor, textColor: 255 },
    head: [["Description", "Amount (INR)"]],
    body: [
      ...(Number(booking.taxes || 0) > 0 
        ? [
            ["Total Amount (incl. Tax)", `Rs. ${Number(booking.totalAmount).toLocaleString()}`],
            ["Net Amount (Base)", `Rs. ${(Number(booking.totalAmount || 0) - Number(booking.taxes || 0)).toLocaleString()}`],
            ["Total Tax", `Rs. ${Number(booking.taxes).toLocaleString()}`],
          ]
        : [
            ["Hall Rental", `Rs. ${Number(booking.totalAmount || 0).toLocaleString()}`],
          ]
      ),
      ...(Number(booking.discount || 0) > 0 ? [["Discount Applied", `- Rs. ${Number(booking.discount).toLocaleString()}`]] : []),
    ],
    foot: [
      ["Total (What Client Pays)", `Rs. ${Number(booking.totalAmount || 0).toLocaleString()}`]
    ],
    footStyles: { fillColor: [241, 245, 249], textColor: textDark, fontStyle: "bold" },
    theme: "grid"
  });

  drawFooter(doc);
  doc.save(`Quotation_${booking.bookingNumber || booking.id}.pdf`);
};

export const generateAgreement = async (data, action = "download") => {
  try {
    const doc = new jsPDF();
    const { booking } = data;
    const settings = await getSettings();
    
    await drawHeader(doc, "CONTRACT AGREEMENT", booking, settings);
  
  doc.setTextColor(...textDark);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Terms & Conditions of Booking", 14, 55);
  
  const clientGst = booking.clientGstNumber || booking.Customer?.gstNumber;
  
  // Custom Table for Contract fields matching the physical format
  const tableData = [
    ["Booking Reference", booking.bookingId || booking.id],
    ["Name of the Host", booking.customerName || "N/A"],
    ...(clientGst && clientGst !== "undefined" && clientGst !== "null" ? [["Client GSTIN", clientGst]] : []),
    ["Date & Time of function", `${booking.date ? new Date(booking.date).toLocaleDateString("en-IN") : "TBD"} | ${booking.session || "Full Day"}`],
    ["Address", booking.address || "N/A"],
    ["Email & Mobile No", `${booking.email || ""} | ${booking.phone || ""}`],
    ["No. of Guests Expected", `${booking.guests || 0} pax`],
    ["Nature of Function", booking.eventType || "N/A"],
    ["Bride Name & Address", `${booking.brideName || ""} ${booking.brideAddress ? "- " + booking.brideAddress : ""}`.trim() || "N/A"],
    ["Groom Name & Address", `${booking.groomName || ""} ${booking.groomAddress ? "- " + booking.groomAddress : ""}`.trim() || "N/A"],
    ["Quoted Amount", `Rs. ${Number((Number(booking.totalAmount || 0) + Number(booking.discount || 0))).toLocaleString()}`],
    ["Discount", `Rs. ${Number(booking.discount || 0).toLocaleString()}`],
    ["Final Total Amount", `Rs. ${Number(booking.totalAmount || 0).toLocaleString()}`],
    ["Advance Paid", `Rs. ${Number(booking.advance || 0).toLocaleString()}`],
    ["Deposit Amount Paid", `Rs. ${Number(booking.depositAmount || 0).toLocaleString()}`],
    ["Balance Amount Payable", `Rs. ${Math.max(0, Number(booking.totalAmount || 0) - Number(booking.advance || 0) - Number(booking.depositAmount || 0)).toLocaleString()}`],
    ["Extra arrangements if any", booking.additionalServices || booking.specialInstructions || "N/A"],
    ["Any Remarks", booking.notes || "N/A"]
  ];

  autoTable(doc, {
    startY: 65,
    theme: "grid",
    body: tableData,
    styles: { fontSize: 9, cellPadding: 2.5 },
    columnStyles: {
      0: { fontStyle: "bold", textColor: primaryColor, fillColor: [248, 250, 252], cellWidth: 70 },
      1: { textColor: textDark }
    },
    alternateRowStyles: { fillColor: [255, 255, 255] },
    margin: { bottom: 30 } // Leave space for signatures
  });

  const finalY = (doc.lastAutoTable && doc.lastAutoTable.finalY) ? doc.lastAutoTable.finalY : 160;

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("Both Parties Agree Terms & Conditions", 14, finalY + 10);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Name & Signature of Host with Date", 14, finalY + 25);
  doc.text("Name & Signature of Venue Representative with Date", 100, finalY + 25);
  
  drawFooter(doc, settings);
  
  if (action === "preview") {
    window.open(doc.output('bloburl'), '_blank');
  } else {
    doc.save(`Agreement_${booking.bookingId || booking.id}.pdf`);
  }
  } catch (err) {
    console.error("PDF Generation Error:", err);
    alert("Failed to generate PDF: " + err.message);
  }
};

export const generateInvoice = async (data) => {
  try {
  const doc = new jsPDF();
  const { booking, payments, totalPaid, outstanding, isRevised } = data;
  const settings = await getSettings();
  
  await drawHeader(doc, isRevised ? "REVISED TAX INVOICE" : "TAX INVOICE", booking, settings);
  
  // Invoice Info
  doc.setTextColor(...textDark);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Bill To:", 14, 55);
  doc.setFont("helvetica", "normal");
  doc.text(`${booking.Customer?.name || booking.customerName || "Customer"}`, 14, 62);
  doc.text(`Phone: ${booking.Customer?.phone || booking.phone || "N/A"}`, 14, 68);
  const clientGst = booking.clientGstNumber || booking.Customer?.gstNumber;
  if (clientGst && clientGst !== "undefined" && clientGst !== "null") {
    doc.text(`GSTIN: ${clientGst}`, 14, 74);
  }
  
  doc.setFont("helvetica", "bold");
  doc.text("Tax Invoice Details:", 120, 55);
  doc.setFont("helvetica", "normal");
  doc.text(`Tax Invoice No: ${booking.bookingId || booking.id}`, 120, 62);
  doc.text(`Status: ${outstanding <= 0 ? "PAID" : "DUE"}`, 120, 68);
  doc.text(`Date: ${data.invoiceDate ? new Date(data.invoiceDate).toLocaleDateString() : new Date().toLocaleDateString()}`, 120, 74);

  const facilities = Array.isArray(booking.facilities) ? booking.facilities : [];
  
  let dynamicBody = [];
  
  // Base event/hall
  let hallTotal = Number(booking.totalAmount || 0);
  
  // Deduct facility prices from hallTotal to get the actual hall cost
  facilities.forEach(f => {
    hallTotal -= (Number(f.price || 0) * Number(f.count || 1));
  });
  
  // In the hybrid inclusive model, totalAmount is the overall total.
  // The taxes were calculated based on the raw prices.
  const totalTax = Number(booking.taxes || 0);
  
  // We'll calculate the printed base as Total - Tax
  const baseAmount = Math.max(0, Number(booking.totalAmount || 0) - totalTax);
  
  // We don't have the exact split of tax in the document, so we approximate the hall base
  // by subtracting the exact facility bases from the overall base.
  let exactFacTax = 0;
  let facTotal = 0;
  facilities.forEach(f => {
    const p = Number(f.price || 0) * Number(f.count || 1);
    facTotal += p;
    const gstRate = Number(f.gst || 0);
    if (gstRate > 0) exactFacTax += (p * gstRate) / 100;
  });
  
  const hallTax = Math.max(0, totalTax - exactFacTax);
  const hallBase = Math.max(0, baseAmount - (facTotal - exactFacTax));
  
  // Find configured hall tax percentage
  let hallTaxPct = Number(booking.taxPercentage);
  if (!hallTaxPct && settings.halls) {
    const selectedHall = settings.halls.find(h => h.name === booking.hall);
    if (selectedHall) {
      hallTaxPct = selectedHall.gstRate !== undefined ? selectedHall.gstRate : 18;
    }
  }
  if (!hallTaxPct) hallTaxPct = 18; // Force fallback to 18% as requested
  
  dynamicBody.push([
    `${booking.eventType || "Event"} at ${booking.hall || "Venue"}`,
    "1",
    booking.session || "-",
    hallBase.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 }),
    hallTax > 0 ? `${hallTax.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} (${hallTaxPct}%)` : "-",
    (hallBase + hallTax).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })
  ]);

  // Facilities
  facilities.forEach(f => {
    const count = Number(f.count || 1);
    const p = Number(f.price || 0) * count;
    const gstRate = Number(f.gst || 0);
    const gstAmt = (p * gstRate) / 100;
    const fBase = p - gstAmt;

    dynamicBody.push([
      f.name,
      count.toString(),
      f.time || "-",
      fBase.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 }),
      gstRate > 0 ? `${gstAmt.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} (${gstRate}%)` : "-",
      p.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })
    ]);
  });

  if (Number(booking.discount || 0) > 0) {
    dynamicBody.push([
      "Discount Applied", "-", "-", "-", "-",
      `- ${Number(booking.discount).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
    ]);
  }

  // Summary Table
  autoTable(doc, {
    startY: 80,
    headStyles: { fillColor: primaryColor, textColor: 255 },
    head: [["Item Description", "Qty", "Time", "Base (INR)", "GST (INR)", "Total (INR)"]],
    body: dynamicBody,
    foot: [
      ["Gross Total", "", "", "", "", `${Number(booking.totalAmount || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`],
      ["Total Paid", "", "", "", "", `${Number(totalPaid || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`],
      ["Balance Due", "", "", "", "", `${Number(outstanding || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`]
    ],
    footStyles: { fillColor: [248, 250, 252], textColor: textDark, fontStyle: "bold" },
    theme: "grid"
  });

  // Payment History
  if (payments && payments.length > 0) {
    const startY = (doc.lastAutoTable ? doc.lastAutoTable.finalY : 100) + 15;
    doc.text("Payment History", 14, startY);
    const payBody = payments.map(p => {
      let dateStr = "";
      try { dateStr = new Date(p.paymentDate || p.createdAt || Date.now()).toLocaleDateString(); } catch(e) { dateStr = "-"; }
      return [
        dateStr,
        p.Receipt?.receiptNumber || p.referenceNumber || "-",
        p.paymentMode || "Cash",
        `Rs. ${Number(p.amount || 0).toLocaleString()}`
      ];
    });
    
    autoTable(doc, {
      startY: startY + 5,
      headStyles: { fillColor: [100, 116, 139] },
      head: [["Date", "Receipt No", "Mode", "Amount"]],
      body: payBody,
      theme: "grid"
    });
  }

  // Bank Details
  if (settings.bankName && settings.accountNumber) {
    const finalY = doc.lastAutoTable ? doc.lastAutoTable.finalY + 15 : 200;
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("Bank Details for Payment:", 14, finalY);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Bank Name: ${settings.bankName}`, 14, finalY + 6);
    doc.text(`Account Name: ${settings.accountName || settings.legalName || settings.venueName}`, 14, finalY + 11);
    doc.text(`Account No: ${settings.accountNumber}`, 14, finalY + 16);
    doc.text(`IFSC Code: ${settings.ifscCode || "N/A"}`, 14, finalY + 21);
  }

  drawFooter(doc, settings);
  doc.save(`Tax_Invoice_${booking.bookingId || booking.id || "001"}.pdf`);
  } catch (err) {
    console.error(err);
    alert("PDF Error: " + err.message);
  }
};

export const generateReceiptSummary = async (data) => {
  const doc = new jsPDF();
  const { booking, payments } = data;
  const settings = await getSettings();
  
  await drawHeader(doc, "RECEIPT SUMMARY", booking, settings);
  
  doc.setTextColor(...textDark);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(`Payment Ledger`, 14, 55);
  
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`Customer: ${booking.Customer?.name || booking.customerName}`, 14, 65);
  doc.text(`Total Paid: Rs. ${data.totalPaid?.toLocaleString() || 0}`, 14, 72);

  if (!payments || payments.length === 0) {
    doc.text("No payments recorded yet.", 14, 90);
  } else {
    const payBody = payments.map(p => [
      new Date(p.createdAt).toLocaleDateString(),
      p.Receipt?.receiptNumber || "-",
      p.paymentMode,
      `Rs. ${Number(p.amount || 0).toLocaleString()}`
    ]);
    
      autoTable(doc, {
      startY: 85,
      headStyles: { fillColor: primaryColor, textColor: 255 },
      head: [["Date", "Receipt No", "Mode", "Amount"]],
      body: payBody,
      theme: "grid"
    });
  }
  
  drawFooter(doc, settings);
  doc.save(`Receipt_Summary_${booking.bookingNumber || booking.id}.pdf`);
};

export const generateStatement = (data) => {
  const doc = new jsPDF();
  const { booking, payments } = data;
  
  drawHeader(doc, "CUSTOMER STATEMENT", booking);
  
  doc.setTextColor(...textDark);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(`Booking Ledger Statement`, 14, 55);
  
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`Customer: ${booking.Customer?.name || booking.customerName}`, 14, 65);
  doc.text(`Date Generated: ${new Date().toLocaleDateString()}`, 14, 72);

  const statementBody = [
    [
      new Date(booking.date).toLocaleDateString(),
      "Booking Finalized (Gross Amount)",
      `Rs. ${booking.totalAmount?.toLocaleString() || 0}`,
      "-",
      `Rs. ${booking.totalAmount?.toLocaleString() || 0}`
    ]
  ];

  let runningBalance = booking.totalAmount || 0;
  
  if (payments && payments.length > 0) {
    const sortedPayments = [...payments].sort((a, b) => new Date(a.createdAt) - new Date(b.createdAt));
    sortedPayments.forEach(p => {
      runningBalance -= p.amount;
      statementBody.push([
        new Date(p.createdAt).toLocaleDateString(),
        `Receipt #${p.Receipt?.receiptNumber || "-"} (${p.paymentMode})`,
        "-",
        `Rs. ${Number(p.amount || 0).toLocaleString()}`,
        `Rs. ${Number(runningBalance || 0).toLocaleString()}`
      ]);
    });
  }
  
    autoTable(doc, {
    startY: 85,
    headStyles: { fillColor: primaryColor, textColor: 255 },
    head: [["Date", "Particulars", "Debit", "Credit", "Balance"]],
    body: statementBody,
    theme: "grid"
  });
  
  drawFooter(doc);
  // Open in new tab instead of silent download
  window.open(doc.output('bloburl'), '_blank');
};

export const generateReceipt = async (payment, booking) => {
  const doc = new jsPDF();
  const settings = await getSettings();
  
  // Header
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, 210, 44, "F");

  // Logo / Brand
  doc.setTextColor(255, 255, 255);
  
  let textX = 14;
  if (settings.logoUrl) {
    try {
      const imgData = await fetchImage(settings.logoUrl);
      doc.addImage(imgData, 'PNG', 14, 10, 24, 24);
      textX = 42;
    } catch (e) {
      console.warn("Failed to load logo", e);
    }
  }

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(settings.venueName || "VENUEZA", textX, 14);
  
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text(settings.location || "Premium Venue & Event Management", textX, 20);
  
  let contactStr = [];
  if (settings.phone) contactStr.push(settings.phone);
  if (settings.email) contactStr.push(settings.email);
  
  if (contactStr.length > 0) {
    doc.text(contactStr.join(" | "), textX, 26);
  }

  if (settings.gstin) {
    doc.text(`GSTIN: ${settings.gstin}`, textX, 32);
  }

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("OFFICIAL RECEIPT", 196, 14, { align: "right" });
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`Date: ${new Date(payment.paymentDate || payment.createdAt).toLocaleDateString()}`, 196, 22, { align: "right" });
  doc.text(`Bill No: ${booking?.bookingId || booking?.id || payment.paymentNumber || payment.id}`, 196, 28, { align: "right" });

  // Receipt Body Border
  doc.setDrawColor(200, 200, 200);
  doc.setFillColor(252, 253, 255);
  doc.roundedRect(14, 55, 182, 110, 3, 3, "FD");

  // Content
  doc.setTextColor(...textDark);
  
  // Received From
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("Received with thanks from:", 20, 68);
  
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(`${booking.Customer?.name || booking.customerName || "Customer"}`, 75, 68);
  doc.line(75, 70, 185, 70); // underline

  // The sum of
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("The sum of Rupees:", 20, 82);
  
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  
  // Number to words helper
  const numToWords = (num) => {
    const a = ['','One ','Two ','Three ','Four ', 'Five ','Six ','Seven ','Eight ','Nine ','Ten ','Eleven ','Twelve ','Thirteen ','Fourteen ','Fifteen ','Sixteen ','Seventeen ','Eighteen ','Nineteen '];
    const b = ['', '', 'Twenty','Thirty','Forty','Fifty', 'Sixty','Seventy','Eighty','Ninety'];
    if ((num = num.toString()).length > 9) return 'overflow';
    let n = ('000000000' + num).substr(-9).match(/^(\d{2})(\d{2})(\d{2})(\d{1})(\d{2})$/);
    if (!n) return '';
    let str = '';
    str += (n[1] != 0) ? (a[Number(n[1])] || b[n[1][0]] + ' ' + a[n[1][1]]) + 'Crore ' : '';
    str += (n[2] != 0) ? (a[Number(n[2])] || b[n[2][0]] + ' ' + a[n[2][1]]) + 'Lakh ' : '';
    str += (n[3] != 0) ? (a[Number(n[3])] || b[n[3][0]] + ' ' + a[n[3][1]]) + 'Thousand ' : '';
    str += (n[4] != 0) ? (a[Number(n[4])] || b[n[4][0]] + ' ' + a[n[4][1]]) + 'Hundred ' : '';
    str += (n[5] != 0) ? ((str != '') ? 'and ' : '') + (a[Number(n[5])] || b[n[5][0]] + ' ' + a[n[5][1]]) : '';
    return str.trim() + ' Only';
  };
  
  doc.text(numToWords(payment.amount), 65, 82);
  doc.setDrawColor(200, 200, 200);
  doc.line(65, 84, 185, 84);

  // Towards
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("Towards Booking Ref:", 20, 96);
  doc.setFont("helvetica", "bold");
  doc.text(`${booking.bookingId || booking.id} (${booking.eventType || "Event"})`, 65, 96);
  doc.setDrawColor(200, 200, 200);
  doc.line(65, 98, 185, 98);

  // By Mode
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("By Payment Mode:", 20, 110);
  doc.setFont("helvetica", "bold");
  doc.text(`${payment.paymentMode || "Cash"} ${payment.referenceNumber ? `(Ref: ${payment.referenceNumber})` : ""}`, 65, 110);
  doc.setDrawColor(200, 200, 200);
  doc.line(65, 112, 185, 112);

  // Amount Box
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(20, 135, 60, 20, 2, 2, "F");
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...textDark);
  doc.text(`₹ ${Number(payment.amount || 0).toLocaleString()}/-`, 50, 148, { align: "center" });

  // Signatures
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setDrawColor(100, 116, 139);
  doc.line(130, 148, 185, 148);
  doc.text("Authorized Signatory", 157.5, 154, { align: "center" });
  
  // Thank you note
  doc.setFontSize(10);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(100, 116, 139);
  doc.text("Subject to realization of cheque/draft.", 20, 175);

  drawFooter(doc);
  const receiptNum = payment.Receipts?.[0]?.receiptNumber || payment.Receipt?.receiptNumber || payment.paymentNumber || payment.id;
  doc.save(`Receipt_${receiptNum}.pdf`);
};

export const generateAttendanceReport = async (monthName, year, attendanceData, usersData) => {
  const doc = new jsPDF();
  const settings = await getSettings();

  await drawHeader(doc, "MONTHLY ATTENDANCE REPORT", null, settings);

  doc.setTextColor(...textDark);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Report Details", 14, 56);
  
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...textLight);
  doc.text(`Month: ${monthName} ${year}`, 14, 62);
  doc.text(`Generated On: ${new Date().toLocaleDateString()}`, 14, 67);

  // Group attendance by user
  const monthIndex = new Date(`${monthName} 1, ${year}`).getMonth();
  const daysInMonth = new Date(year, monthIndex + 1, 0).getDate();
  
  const tableData = usersData.map(u => {
    const userRecords = attendanceData.filter(a => a.userId === u.id);
    let presentDays = 0;
    userRecords.forEach(a => {
      if (a.status === "Present" || a.checkIn) presentDays++;
    });
    const absentDays = daysInMonth - presentDays;
    
    return [
      u.name,
      u.role,
      `${presentDays} Days`,
      `${absentDays} Days`
    ];
  });

  autoTable(doc, {
    startY: 75,
    head: [["Staff Name", "Role", "Present", "Absent"]],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [241, 245, 249], textColor: textDark, fontStyle: 'bold', fontSize: 9 },
    bodyStyles: { textColor: [51, 65, 85], fontSize: 9 },
    alternateRowStyles: { fillColor: [250, 250, 250] },
    margin: { left: 14, right: 14 },
    styles: { cellPadding: 5 }
  });

  drawFooter(doc, settings);
  doc.save(`Attendance_Report_${monthName}_${year}.pdf`);
};

export const generateInventoryReport = async (items) => {
  const doc = new jsPDF();
  const settings = await getSettings();

  await drawHeader(doc, "INVENTORY REPORT", null, settings);

  doc.setTextColor(...textDark);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated on: ${new Date().toLocaleDateString("en-IN")}`, 14, 52);
  doc.text(`Total Items: ${items.length}`, 196, 52, { align: "right" });

  const tableBody = items.map(item => [
    item.itemName,
    item.category || "-",
    item.totalQuantity.toString(),
    item.availableQuantity.toString(),
    item.condition,
    item.unitPrice ? `Rs ${parseFloat(item.unitPrice).toLocaleString("en-IN")}` : "-",
    item.notes || "-"
  ]);

  autoTable(doc, {
    startY: 58,
    head: [["Item Name", "Category", "Total Qty", "Available Qty", "Condition", "Unit Price", "Notes"]],
    body: tableBody,
    theme: 'grid',
    styles: { font: "helvetica", fontSize: 9, cellPadding: 4, textColor: textDark },
    headStyles: { fillColor: primaryColor, textColor: [255, 255, 255], fontStyle: 'bold' },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 35 },
      1: { cellWidth: 25 },
      2: { cellWidth: 20, halign: "center" },
      3: { cellWidth: 25, halign: "center", fontStyle: "bold" },
      4: { cellWidth: 20 },
      5: { cellWidth: 25, halign: "right" },
      6: { cellWidth: "auto" }
    },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 3) {
        // Red color if available < 20% of total
        const total = parseFloat(data.row.raw[2]);
        const avail = parseFloat(data.row.raw[3]);
        if (!isNaN(total) && !isNaN(avail) && total > 0 && avail < total * 0.2) {
          data.cell.styles.textColor = [220, 38, 38]; // Red
        } else {
          data.cell.styles.textColor = [5, 150, 105]; // Green
        }
      }
    }
  });

  drawFooter(doc, settings);
  doc.save(`Inventory_Report_${new Date().toISOString().slice(0, 10)}.pdf`);
};
